services:
    postgresql:
        image: postgres:latest
        container_name: 'postgresql_univesp'
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=${PG_PASS}
            - POSTGRES_USER=${PG_USER}
        volumes:
            - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

    pgadmin:
        image: dpage/pgadmin4
        container_name: 'pgadmin_univesp'
        environment:
            PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
            PGADMIN_DEFAULT_PASSWORD: "admin"
        ports:
            - "5050:80"
        depends_on:
            - postgresql